### ISSUE TITLE
Publish documentation at hendrics.stingray.science

### ISSUE THREAD

**Issue by jdswinbank** [StingraySoftware/HENDRICS#101]
As per https://github.com/StingraySoftware/StingraySoftware.github.io/issues/15#issuecomment-827002282, if you visit https://docs.readthedocs.io/en/stable/custom_domains.html#custom-domain-support and follow steps 2 through 4, HENDRICS documentation should automatically be published at https://hendrics.stingray.science. Which would be nice.

If that works, perhaps file an issue against Stingray so that we can move its documentation to a matching URL (docs.stingray.science or library.stingray.science or something, I guess).

**Comment by matteobachetti** [comment]
https://hendrics.stingray.science/en/stable/
Thanks @jdswinbank!
