### ISSUE TITLE
HENaccelsearch and --delta-z argument

### ISSUE THREAD

**Issue by giallixx** [StingraySoftware/HENDRICS#106]
Command HENaccelsearch used with fractional value of --delta-z gives the following error: 

HENaccelsearch --fmin 0.33 --fmax 0.37 --delta-z 0.5 Mur19_xmm_epn_det04_ev.nc --nproc 4 --interbin
/home/gianluca/stingray/lib64/python3.6/site-packages/hendrics/efsearch.py:1681: UserWarning: The accelsearch functionality is experimental. Use with care,  and feel free to report any issues.
  "The accelsearch functionality is experimental. Use with care, "
usage: HENaccelsearch [-h] [--outfile OUTFILE] [--emin EMIN] [--emax EMAX]
                      [--fmin FMIN] [--fmax FMAX] [--nproc NPROC]
                      [--zmax ZMAX] [--delta-z DELTA_Z] [--interbin]
                      [--pad-to-double] [--loglevel LOGLEVEL] [--debug]
                      fname
HENaccelsearch: error: argument --delta-z: invalid int value: '0.5'

**Comment by matteobachetti** [comment]
Thanks @giallixx! This is definitely a bug, I'll fix it shortly
