### ISSUE TITLE
output csv file for HENaccelsearch

### ISSUE THREAD

**Issue by giallixx** [StingraySoftware/HENDRICS#109]
I noticed that, in the case of NuSTAR data, the csv file (output of the program HENaccelsearch)  has 18 headers fields separated by "," but 19 values separated by a "," .
This is due to the instr field which is : "fpma , fpmb"  
This originates a bit of confusion when reading the csv file.  

----------------- EXAMPLE of CSV file --------------------------------------- 
time,length,frac_exposure,power,prob,frequency,fdot,fddot,ntrial,emin,emax,fmin,fmax,zmax,mission,instr,mjdref,pepoch
300434644.93175435,328172.22099763324,0.5213423868312758,30.809007592127596,0.0013388150053156302,0.3592762959691531,5.571185483698354e-11,0.0,6563,3.0,15.0,0.35,0.37,100,nustar,"fpma,fpmb",55197.00076601852,58674.25360087679

**Comment by matteobachetti** [comment]
Hi @giallixx. Most CSV readers should recognize that "fpma,fpmb" are inside quotes, which means that they are a single string. What are you using?

**Comment by giallixx** [comment]
likely the most used under Linux distributions,  awk
