### ISSUE TITLE
HENDRICS 7.0's HENzsearch fast algorithm

### ISSUE THREAD

**Issue by Gwenloyer** [StingraySoftware/HENDRICS#138]
**Describe the bug**
Updated yesterday stingray and hendrics to the latest update. and found 2 issues.
When using the fast algorithm  from HENzsearch , the program does not select the highest peak , meaining there is a  peak that exceed the threshold but it is not the one selected by HENdrics, when plotting the results of the zsearch , the dotted line are aligned with a small peak or even nothing (in the f space, fdot space  alignement is not bugged) and the peak is also ignored when listing best candidates . 
Also changing the oversample rate used to change the size of the time bin in Hendrics 6.0 , but now it doesn't do that anymore .
Both of hose problems do not exist for normal Zsearch (i.e. without --fast ) which works perfectly fine.

**Comment by Gwenloyer** [comment]
--nbin doesn't work either

**Comment by matteobachetti** [comment]
Hi @Gwenloyer, thanks for the detailed report! A couple of followup questions:
1. Highest peak not selected: I will try to understand what is going on there, I haven't noticed the issue if not in cases where the peaks were very small (compatible with noise)
2. Oversample rate should not change the time bin, just the frequency bins. Could you clarify what you mean by "time bin"?
3. Same goes for nbin: where are you measuring the number of bins? Please note that, e.g., `HENplot` does not use the same nbin used during the search. 
Thanks in advance for your help
