### ISSUE TITLE
CPD and Xspec HENDRICS errors

### ISSUE THREAD

**Issue by annacoerver** [StingraySoftware/HENDRICS#27]
Hi Matteo, Daniela, and anyone who may know the answers to these questions!

I have been getting two errors with HENDRICS (see attached screenshots). The first is a tseg error when I try to generate cross power spectra. My dt values are equal for module A and B, but the tsegs are different. Our event file GTIs are different lengths, could that contribute? 

I am also getting an error when I try to write the final pickle files into an xspec file. I updated numpy using anaconda in both python 3.6 and 2.7. I ran the command in both environments and it still is not working. Any other things I could try or insights into what may be wrong?

Thanks so much!
Anna

![cpds_error](https://user-images.githubusercontent.com/33760735/33220164-2b8250f6-d114-11e7-9e91-1ca21ce7e19f.jpg)

<img width="932" alt="screen shot 2017-11-24 at 12 20 34 pm" src="https://user-images.githubusercontent.com/33760735/33220138-04593e5e-d114-11e7-8a00-cf65840b8c5a.png">

**Comment by matteobachetti** [comment]
Hi @annacoerver, have you by any chance used the `--safe-interval` option? We just found a bug that _might_ be related to your `tseg` error.
For the numpy error, you are still executing MP2xspec (from the old MaLTPyNT) and not in an Anaconda environment. Is the error still present in an up-to-date environment and using HEN2xspec?

**Comment by annacoerver** [comment]
I did use the --safe-interval option, and will try regenerating the light curves without that. 

I think the documentation for HENDRICS still says MP2xspec, I tried HEN2xspec and that works! Thanks!

**Comment by matteobachetti** [comment]
Oops, I need to update the docs, sorry about that!

**Comment by matteobachetti** [comment]
I think everything was solved here, so I close. @annacoerver feel free to reopen if I forgot something!
