### ISSUE TITLE
HENrebin

### ISSUE THREAD

**Issue by abigailStev** [StingraySoftware/HENDRICS#40]
Issue raised by Paul Ray via email: "The only problem I've been having is with HENrebin, which I can't seem to control right.  I always get way too few bins regardless of the argument."

**Comment by matteobachetti** [comment]
@paulray could you expand on this?

**Comment by abigailStev** [comment]
@paulray For a rebin factor of 1.04, are you specifying 1.04 or 0.04? In HENDRICS it should be 0.04 (as in 1+0.04).

**Comment by bwgref** [comment]
Bump

**Comment by matteobachetti** [comment]
Fixed in #74
