### ISSUE TITLE
HENfspec Tseg Error

### ISSUE THREAD

**Issue by annacoerver** [StingraySoftware/HENDRICS#52]
The HENDRICS error is as follows:
![cpds_error 1 1](https://user-images.githubusercontent.com/33760735/48795929-42066900-eccc-11e8-9db9-997f5f8b5ee5.png)

I think that this comes from an oddity/error in the original event files themselves -- the start time, stop time, and total exposure time for module A is 3 seconds off from module B for the source I'm working with. I have never gotten this error for any other sources, and it only occurs during CPDS generation. I'm not sure why MALTPYNT works for this source but HENDRICS doesn't, because MALTPYNT generated the cpds just fine.

**Comment by matteobachetti** [comment]
Ok. Found the critical point. We are making the necessary modifications!

**Comment by matteobachetti** [comment]
@annacoerver please take a look now!

**Comment by annacoerver** [comment]
Thanks so much!
