### ISSUE TITLE
"passing an empty time array to create_gti_mask" error when extracting a light curve

### ISSUE THREAD

**Issue by paopaofi** [StingraySoftware/HENDRICS#62]
when I tried to extract a light curve from a nicer observation (ObsID: 1130360117). 

following error message popped out:
"error: passing an empty time array to create_gti_mask"

steps to repeat: 

1. get "ni1130360117_0mpu7_cl.evt" file from archive.

2. using HENreadevents and HENcalibrate to generate file    "ni1130360117_0mpu7_cl_nicer_xti_ev_calib.nc"

3. then run:
$HENlcurve ni1130360117_0mpu7_cl_nicer_xti_ev_calib.nc -b -8 -e 1 10

**Comment by matteobachetti** [comment]
This got fixed at some point. I tried to reproduce the failure, with the same data file, and it worked. Closing!
