### ISSUE TITLE
 issues in save_as_xspec.py

### ISSUE THREAD

**Issue by ellot** [StingraySoftware/HENDRICS#68]
As shown in the tutorials, if the power spectrum is rebinned with log binning. I think these two lines (line 39, line 40) in the save_as_xspec.py are not right since the _df_ is not constant. 

_39 power = contents.power.real * contents.df
40 power_err = contents.power_err.real * contents.df_

**Comment by matteobachetti** [comment]
df can be an array. In that case, you just multiply the two arrays power and df

**Comment by matteobachetti** [comment]
Closing. Feel free to re-open if I did not understand your point!
